<?php 
global $browser_title;
 $browser_title = 'GEFS';   
 include '../portal_header.php';?>
 
<?php include 'gefs/sidebar.php'?>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2"></h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <!--<button type="button" class="btn btn-sm btn-outline-secondary">Share</button>-->
            <button id="export" type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
        </div>
      </div>
<img src="../../pages/disclaimer/disclaimer_small.png" style="display: block; margin: auto; width: 80%;" />

     <h2 id="section-title"><center>Global Ensemble Forecast System</center></h2>
     	<div id="description">
				<p style="margin-left:0px; margin-right:0px; text-align:start"><span style="font-size:14.4px"><span style="color:#000000"><span style="font-family:Arial,Helvetica,sans-serif"></span></span></span></p>

<!--<center style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:24px;"><span style="font-family:arial,helvetica,sans-serif;"><u>Global Ensemble Forecast System (GEFS)</u></span></span></center>-->

<p style="margin-left:0px; margin-right:0px; text-align:center"><img src="https://www.emc.ncep.noaa.gov/emc/images/forcast_system_icons/animated/gefs_animated.gif" style="border: 0px none; box-sizing: border-box; vertical-align: middle;"></p>


<p style="margin-left:0px; margin-right:0px"><span style="font-family:arial,helvetica,sans-serif;"><span style="font-size:12px;">To illustrate the use of ensemble based probabilistic forecast, the relative measure of predictability (RMOP, Toth et al. 2003), is shown in the above animation from the GEFS run from 0000 UTC 4 November 2020, out to 15 days (360 hours). Considering the 120-h forecast valid at 0000 UTC 9 November 2020, the shading indicates the RMOP of the ensemble mean 500-hPa height at each grid point, compared to ensemble forecasts of 500-hPa height over the previous 30 days. These are in 10% increments as indicated by the color bar at the bottom of the graphic. Shading at 90% indicates that at least 9 of 10 ensemble forecasts in the past 30 days had fewer ensemble members in the same "bin" as the ensemble mean than the present forecast. The blue numbers over each box represents the percentage of time that a forecast with the given degree of predictability has verified over the past 30 days. Here, over the 90% predictability box we see that only 61-84% of the forecasts with 90% relative predictability at 120 hours have verified in the same climatological bin as the observed 500-hPa height at 120 hours over the past 30 days. Note that in general, the values are generally lower than the RMOP numbers below the bar. This is because the underlying forecast model is imperfect, the initial conditions are imprecise, and the atmosphere behaves chaotically.</span></span><br>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%; page-break-before: always" lang="en-GB" align="justify"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><span lang="en-US"><b>1. Introduction / History</b></span></span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px none; outline: 0px none; background: transparent none repeat scroll 0% 0%; vertical-align: baseline; font-family: &quot;Open Sans&quot;,Helvetica,Verdana,Arial,sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">The Global Ensemble Forecast System (GEFS) has been operational at NCEP since December 1992, with the initial version using the NCEP Global Spectral Model (GSM) at T62L18 resolution (about 200km in horizontal and 18 vertical sigma levels) and the initial condition perturbations (2 pairs perturbed and 1 control members) were generated by breeding vector (BV) method (Toth and Kalnay 1993; Toth and Kalnay 1997; Toth et al. 1997; Toth et al. 2001; Zhu et al. 2002; Buizza et al. 2005; Zhu 2005). The GEFS ran once per day, out to 12 days in the early 90s. During the early 2000s, the 1st generation of GEFS reforecast (1979 - 2006) was produced off-line from using NCEP GFS/GEFS 1998 model version by NOAA PSL (Hamill et al. 2006) to demonstrate the improved ensemble reliability through bias correction and calibration.</span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px none; outline: 0px none; background: transparent none repeat scroll 0% 0%; vertical-align: baseline; font-family: &quot;Open Sans&quot;,Helvetica,Verdana,Arial,sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">In August 2005, the GEFS was upgraded to run four times per day (0000, 0600, 1200 and 1800 UTC) and produced forecasts out to 16 days. Each of these cycles have 10 (5 pairs) perturbed members that were initialized using BV method and cycled every 6 hours. If tropical cyclones were present in the initial times, a tropical storm relocation (TSR) technique was applied to each ensemble member to adjust the initial central location to the observed location (Liu et al. 2006). An extended BV method with Ensemble Transform and Rescaling (BV-ETR) (Wei et al. 2006; 2008) and 6-hour cycling was implemented operationally in 2006.</span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px none; outline: 0px none; background: transparent none repeat scroll 0% 0%; vertical-align: baseline; font-family: &quot;Open Sans&quot;,Helvetica,Verdana,Arial,sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">In early 2010, the GEFS was upgraded with enhanced representation of model uncertainty using the Stochastic Total Tendency Perturbation (STTP) algorithm (Hou et al., 2008). The stochastic tendency perturbations were updated every 6 hours. Meanwhile, the  2nd generation of NOAA GEFS reforecasts were produced off-line for 29 years (1985 - 2013) by NOAA PSL (Hamill et al. 2013; <a href="https://psl.noaa.gov/forecasts/reforecast2/">NOAA/PSL reforecast website</a>) using GEFS v10 configurations and CFS reanalysis.</span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px none; outline: 0px none; background: transparent none repeat scroll 0% 0%; vertical-align: baseline; font-family: &quot;Open Sans&quot;,Helvetica,Verdana,Arial,sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Through another major upgrade in December 2015, the GEFS initial perturbations were chosen from the operational hybrid Global Data Assimilation System (GDAS) 80-member Ensemble Kalman Filter (EnKF; Whitaker et al., 2008) 6-h forecasts along with tropical storm relocation and centralization of the initial perturbations (Zhou et al. 2016; 2017).</span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px none; outline: 0px none; background: transparent none repeat scroll 0% 0%; vertical-align: baseline; font-family: &quot;Open Sans&quot;,Helvetica,Verdana,Arial,sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Details on each GEFS upgrade can be found in the <a href="https://www.emc.ncep.noaa.gov/gmb/yzhu/html/ENS_IMP.html">GEFS implementation log</a>. Evolution of the GEFS configurations to date are summarized in the table below:</span></span></p>

<table class=a border=1 cellspacing=0 cellpadding=0 width=719 style='border-collapse:
 collapse;mso-table-layout-alt:fixed;border:none;mso-border-alt:solid white 1.0pt;
 mso-yfti-tbllook:1056;mso-padding-alt:5.0pt 5.0pt 5.0pt 5.0pt;mso-border-insideh:
 1.0pt solid white;mso-border-insidev:1.0pt solid white'>
 <tr style='mso-yfti-irow:-1;mso-yfti-firstrow:yes;mso-yfti-lastfirstrow:yes;
  height:25.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-bottom:solid white 3.0pt;
  background:#5B9BD5;padding:1.0pt 3.0pt 1.0pt 3.0pt;height:25.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:1'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>Version</span></b><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:white'><o:p></o:p></span></b></p>
  </td>
  <td width=72 style='width:.75in;border-top:solid white 1.0pt;border-left:
  none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#5B9BD5;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:25.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:1'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>Implementation </span></b><b style='mso-bidi-font-weight:
  normal'><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:white'><o:p></o:p></span></b></p>
  </td>
  <td width=80 style='width:60.0pt;border-top:solid white 1.0pt;border-left:
  none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#5B9BD5;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:25.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:1'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>Initial uncertainty </span></b><b style='mso-bidi-font-weight:
  normal'><span lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:white'><o:p></o:p></span></b></p>
  </td>
  <td width=72 style='width:.75in;border-top:solid white 1.0pt;border-left:
  none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#5B9BD5;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:25.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:1'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>TS relocation</span></b><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:white'><o:p></o:p></span></b></p>
  </td>
  <td width=81 style='width:60.75pt;border-top:solid white 1.0pt;border-left:
  none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#5B9BD5;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:25.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:1'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>Model Uncertainty</span></b><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:white'><o:p></o:p></span></b></p>
  </td>
  <td width=149 style='width:111.75pt;border-top:solid white 1.0pt;border-left:
  none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#5B9BD5;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:25.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:1'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>Resolution </span></b><b style='mso-bidi-font-weight:
  normal'><span lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:white'><o:p></o:p></span></b></p>
  </td>
  <td width=51 style='width:38.25pt;border-top:solid white 1.0pt;border-left:
  none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#5B9BD5;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:25.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:1'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>FCST length </span></b><b style='mso-bidi-font-weight:
  normal'><span lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:white'><o:p></o:p></span></b></p>
  </td>
  <td width=77 style='width:57.75pt;border-top:solid white 1.0pt;border-left:
  none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#5B9BD5;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:25.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:1'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>Ens. size (members) </span></b><b style='mso-bidi-font-weight:
  normal'><span lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:white'><o:p></o:p></span></b></p>
  </td>
  <td width=75 style='width:56.25pt;border-top:solid white 1.0pt;border-left:
  none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#5B9BD5;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:25.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:1'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>Daily frequency </span></b><b style='mso-bidi-font-weight:
  normal'><span lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:white'><o:p></o:p></span></b></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:0;height:19.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>V1.0</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>1992.12</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=80 rowspan=7 style='width:60.0pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:1.0pt 3.0pt 1.0pt 3.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>Bred
  vector </span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 rowspan=6 style='width:.75in;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>None</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=81 rowspan=8 style='width:60.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>None</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=149 style='width:111.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:1.0pt 3.0pt 1.0pt 3.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T62L18
  ~200km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=51 style='width:38.25pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>12</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=77 style='width:57.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>2+1</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=75 style='width:56.25pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>00UTC</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:1;height:19.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>V2.0</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>1994.03</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=149 rowspan=2 style='width:111.75pt;border-top:none;border-left:
  none;border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;
  mso-border-top-alt:solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;
  background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T62L18
  ~200km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=51 rowspan=10 style='width:38.25pt;border-top:none;border-left:
  none;border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;
  mso-border-top-alt:solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;
  background:#E9EFF7;padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>16</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=77 rowspan=2 style='width:57.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>10+1
  (00UTC)</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>4+1
  (12UTC)</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=75 rowspan=4 style='width:56.25pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>00UTC</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>12UTC</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:2;height:35.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:35.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>V3.0</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:35.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>2000.06</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:3;height:29.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>V4.0</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>2001.01</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=149 style='width:111.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:1.0pt 3.0pt 1.0pt 3.0pt;height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T126L28(0-2.5)
  ~100km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T62L28(2.5-16)
  ~200km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=77 rowspan=3 style='width:57.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>10+1</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:4;height:29.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>V5.0</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>2004.03</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=149 style='width:111.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:1.0pt 3.0pt 1.0pt 3.0pt;height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T126(0-3.5)
  ~100km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T62L28(3.5-16)
  ~200km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:5;height:29.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>V6.0</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;padding:2.0pt 5.0pt 2.0pt 5.0pt;
  height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>2005.08</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=149 style='width:111.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:1.0pt 3.0pt 1.0pt 3.0pt;height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T126L28(0-7.5)
  ~100km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T62L28(7.5-16)
  ~200km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=75 style='width:56.25pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p>&nbsp;</o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:6;height:19.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>V7.0</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>2006.05</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 rowspan=5 style='width:.75in;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>TSR</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=149 rowspan=2 style='width:111.75pt;border-top:none;border-left:
  none;border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;
  mso-border-top-alt:solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;
  background:#D0DEEF;padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T126L28
  ~100km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=77 style='width:57.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>14+1</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=75 rowspan=6 style='width:56.25pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:19.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>00UTC</span></b><span lang=EN style='font-size:14.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>06UTC</span></b><span lang=EN style='font-size:14.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>12UTC</span></b><span lang=EN style='font-size:14.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>18UTC </span></b><span lang=EN style='font-size:14.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'>(16 days)</span></b><span lang=EN style='font-size:14.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p>&nbsp;</o:p></span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p>&nbsp;</o:p></span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p>&nbsp;</o:p></span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p>&nbsp;</o:p></span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p>&nbsp;</o:p></span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:red'>00UTC (35 days)</span></b><span lang=EN style='font-size:
  14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;
  color:black'><o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:7;height:20.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:20.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>V8.0</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:20.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>2007.03</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=80 rowspan=3 style='width:60.0pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:1.0pt 3.0pt 1.0pt 3.0pt;height:20.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>(BV-
  ETR)</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=77 rowspan=4 style='width:57.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:20.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>20+1</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:8;height:21.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:21.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>V9.0</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:21.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>2010.02</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=81 rowspan=3 style='width:60.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:21.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>STTP</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=149 valign=top style='width:111.75pt;border-top:none;border-left:
  none;border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;
  mso-border-top-alt:solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;
  background:#D0DEEF;padding:2.0pt 5.0pt 2.0pt 5.0pt;height:21.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T190L28
  ~70k<o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:9;height:29.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>V10.0</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>2012.02</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=149 style='width:111.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:1.0pt 3.0pt 1.0pt 3.0pt;height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T254L42
  (0-8) ~50km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>T190L42
  (8-16) ~70km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:10;height:29.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>V11.0</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>2015.12</span><span
  lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=80 rowspan=2 style='width:60.0pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:red'><o:p>&nbsp;</o:p></span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:red'><o:p>&nbsp;</o:p></span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span class=SpellE><b style='mso-bidi-font-weight:
  normal'><span lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:red'>EnKF</span></b></span><b
  style='mso-bidi-font-weight:normal'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:red'>
  (f06)</span></b><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=149 style='width:111.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#D0DEEF;
  padding:1.0pt 3.0pt 1.0pt 3.0pt;height:29.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>TL574L64
  (0-8) ~33km</span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:64'><span lang=EN style='font-size:11.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'>TL382L64
  (8-16) ~50km </span><span lang=EN style='font-size:14.0pt;font-family:"Calibri",sans-serif;
  mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:11;mso-yfti-lastrow:yes;height:11.0pt'>
  <td width=62 style='width:46.5pt;border:solid white 1.0pt;border-top:none;
  mso-border-top-alt:solid white 1.0pt;background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:11.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:red'>V12.0*</span></b><span lang=EN style='font-size:14.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;padding:1.0pt 3.0pt 1.0pt 3.0pt;
  height:11.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:red'>2020.10</span></b><span lang=EN style='font-size:14.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=72 style='width:.75in;border-top:none;border-left:none;border-bottom:
  solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:solid white 1.0pt;
  mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;padding:2.0pt 5.0pt 2.0pt 5.0pt;
  height:11.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:red'>None</span></b><span lang=EN style='font-size:14.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=81 style='width:60.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:11.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:red'>SPPT+SKEB</span></b><span lang=EN style='font-size:14.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=149 style='width:111.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:1.0pt 3.0pt 1.0pt 3.0pt;height:11.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:red'>C384L64 (0-35) ~25km</span></b><span lang=EN
  style='font-size:14.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=51 style='width:38.25pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:11.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:red'>16(35)</span></b><span lang=EN style='font-size:14.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
  <td width=77 style='width:57.75pt;border-top:none;border-left:none;
  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;mso-border-top-alt:
  solid white 1.0pt;mso-border-left-alt:solid white 1.0pt;background:#E9EFF7;
  padding:2.0pt 5.0pt 2.0pt 5.0pt;height:11.0pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal;
  mso-pagination:none;mso-yfti-cnfc:128'><b style='mso-bidi-font-weight:normal'><span
  lang=EN style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
  Calibri;color:red'>30+1+1</span></b><span lang=EN style='font-size:14.0pt;
  font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri;color:black'><o:p></o:p></span></p>
  </td>
 </tr>
</table>
<p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><span lang="en-US"><b>2. Current Status</b></span></span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px none; outline: 0px none; background: transparent none repeat scroll 0% 0%; vertical-align: baseline; font-family: &quot;Open Sans&quot;,Helvetica,Verdana,Arial,sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">On September 23, 2020, GEFS version 12 was implemented into NCEP operations with several significant upgrades. It is the first global-scale coupled system at NCEP, as it includes the integration of the Global Wave Ensemble System (GWES) via one-way coupling to the atmospheric model via the NEMS mediator. Additionally, a special 32th unperturbed GEFS forecast (<a href="https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/gefs_aero.php">GEFS-Aerosol</a>) is run to 5 days with the GSDCHEM chemistry component via one-way coupling to the atmospheric model. These two will replace the existing standalone Global Wave Ensemble and the NEMS GFS Aerosol Component (NGAC) systems. GEFS v12 runs 4 times per day (00; 06; 12; 18UTC) with 31 members at each lead-time at C384L64 (about 25 km horizontal resolution and 64 vertical hybrid levels for atmosphere component) and out to 16 days at each cycle, except for 35 days at 0000 UTC.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><span lang="en-US"><b>3. Configuration of GEFS Version 12</b></span></span></span></p>

<ul>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Replace the Global Spectral Model with the global FV3 dynamical core (<a href="https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/gfs.php">GFSv15.1 version</a>);</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Upgrade the physical parameterization schemes to those implemented with GFSv15.1, including new Geophysical Fluid Dynamics Laboratory (GFDL) microphysics;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Replace the Stochastic Total Tendency Perturbation (STTP) scheme with the new model perturbation techniques including 5-scale Stochastic Perturbation of Physical Tendencies (SPPT) scheme and Stochastic Kinetic Energy Backscatter (SKEB) scheme (Buizza et al. 1999; Berner et al. 2009; Zhu et al. 2019; Zhou et al. 2019);</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Introduce “2-tiered” SST approach for lower boundary conditions over the ocean by considering an evolving ocean SST state with gradual changes with lead time. The 2-tiered SST approach relaxes the SST analysis to a bias-corrected SST prediction from the operational Climate Forecast System v2 (Saha et al., 2010)</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Expand the number of ensemble members from 21 (20 perturbed and 1 unperturbed/control) to 31 (30 perturbed and 1 unperturbed/control) members;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Increase model horizontal resolution to 0.25 degree (~25 km) and maintain the same resolution throughout the forecast period for the atmosphere;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Improved interpolation of grib2 files from the model’s native Gaussian grid;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Removal of lower resolution output, and inclusion of new 0.25deg output onto NCEP web services;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Add forecast guidance for weeks 3-4 for the atmospheric model only. For the 00Z cycle, the forecast length will extend to 35 days with the same 31 ensemble members and uniform horizontal resolution;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Tropical cyclone relocation was removed;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">A 20 year (2000-2019) reanalysis and 31 year (1989-2019) reforecast (Guan et al. 2020; Li et al. 2020) have been produced to support forecast calibration and other applications.</span></span></li>
</ul>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;, Helvetica, Verdana, Arial, sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">GWES changes in GEFS version 12 include:</span></span></span></p> 

<ul>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Spherical spatial grid with increased resolution from 0.5 to 0.25 degree on average;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Increase in number of members from 21 to 31;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Extended the forecast range from 10 to 16 days;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Increased wind field intake stride from 3h to 1h due to coupling;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Improved physics from source-term coefficients that were tuned using an objective framework;</span></span></li>
</ul>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;, Helvetica, Verdana, Arial, sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Details on the coupled Aerosol Model and upgrades over the NGAC system:</span></span></span></p> 

<ul>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">System renamed GEFSv12-Aerosol;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Increase in horizontal resolution from 1 degree to 0.25-degree (25 km) resolution grid;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Update to the latest version of NASA/ESRL GOCART aerosol model;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Implementation of the ARL Fengsha dust emissions model;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Use of Global Biomass Burning Emissions Product extended (GBBEPx) directly on the FV3 grid;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Update the sulfate anthropogenic emissions to the Community Emissions Data System (CEDS) 2014 base version;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Increase from 2 to 4 cycles per day;</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Improved interpolation of grib2 files from the model’s native Gaussian grid;</span></span></li>
</ul>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;, Helvetica, Verdana, Arial, sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">For details on GEFS version 12 and earlier upgrades, please refer to <a href="https://www.emc.ncep.noaa.gov/gmb/yzhu/html/ENS_IMP.html"> NCEP Global Ensemble Forecast system implementation log</a> for details. Please refer to <a href="https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/gefs_aero.php">GEFS-Aerosol web page</a> for more details on that system.</span></span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;, Helvetica, Verdana, Arial, sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><em><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><strong>4. Where to find GEFS data</strong></span></span></em></p>

<ul>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">The real-time GEFS data is available at:;</span></span></li>
<ul>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">The NCEP <a href="https://ftp.ncep.noaa.gov/data/nccf/com/gens/prod/">FTP site</a></span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">The NCEP <a href="https://nomads.ncep.noaa.gov/">NOMADS </a>(National Operational Model Archive and Distribution System) site with the function of data filtering.</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">For a detailed list of GEFS output available on NCEP NOMADS site and the file inventories, see the <a href="http://www.nco.ncep.noaa.gov/pmb/products/gens/">NCO GEFS Product Inventory Page</a>.</span></span></li>
</ul>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Archived GEFS data is available from the NOAA <a href="https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-ensemble-forecast-system-gefs">National Centers for Environmental Information (NCEI)</a></span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">Selected GEFS data at 0.5 degree is also available through the <a href="https://confluence.ecmwf.int/display/TIGGE">WMO TIGGE data center</a> to support THORPEX (The Observing System Research and Predictability Experiment) TIGGE (Interactive Grand Global Ensemble) project.</span></span></li>
<li><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">The 20 years GEFSv12 reforecast data is available through <a href="https://noaa-gefs-retrospective.s3.amazonaws.com/index.html">this AWS site</a>.</span></span></li>
</ul>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;, Helvetica, Verdana, Arial, sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><em><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><strong>5. Future Plans</strong></span></span></em></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;, Helvetica, Verdana, Arial, sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">GEFS v12 is the final upgrade of a global ensemble system separate from the deterministic GFS at NCEP. The next GEFS upgrade will be merged with the version 17 upgrade of the GFS upgrade planned for 2023-2024.</span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;, Helvetica, Verdana, Arial, sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><b><i>6. Other NCEP GEFS web pages:</b></i></span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;, Helvetica, Verdana, Arial, sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;">-<strong> Official GEFS Graphics at the <a href="http://mag.ncep.noaa.gov/model-guidance-model-area.php#">NCEP Model Analysis and Guidance Page : Mean/Spread and Spaghetti Plots</a></strong></span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;, Helvetica, Verdana, Arial, sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><strong>- <a href="http://www.emc.ncep.noaa.gov/users/meg/gefs_plumes">Experimental GEFS plume diagram web page</a></strong></span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;, Helvetica, Verdana, Arial, sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><strong>- <a href="https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/gefs/faq.php">GEFS FAQ Page</a></strong></span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;, Helvetica, Verdana, Arial, sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><strong>- See the "Comprehensive List of Ensemble Web Sites" link above for a list of US (Government/Academic) and international ensemble information</strong></span></span></p>

<p class="teaser" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; background: transparent; vertical-align: baseline; font-family: &quot;Open Sans&quot;,Helvetica,Verdana,Arial,sans-serif; color: rgb(68, 68, 68); line-height: 1.556em; text-rendering: auto;"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><strong>- NCEP <a href="https://www.emc.ncep.noaa.gov/users/verification/global/" style="text-decoration:underline;">Global Model Verification Portal</a>, including GEFS and NAEFS Verification Pages</strong></span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><big>Please send any comments and suggestions about GEFS to <a href="mailto:Yuejian.Zhu@noaa.gov">Yuejian Zhu. </a></big></span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"></span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify">&nbsp;</p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><span lang="en-US"><b><i>7. References for GEFS, NAEFS and post processing:</i></b></span></span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"></span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><a href="http://www.emc.ncep.noaa.gov/gc_wmb/wli/html/doc_journal.html"><b>Link to a comprehensive list of publications since 1995</b></a></span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Berner, J., G.J. Shutts, M. Leutbecher, and T.N. Palmer. 2009. A spectral stochastic kinetic energy backscatter scheme and its impact on flow-dependent predictability in the ECMWF ensemble prediction system. Journal of the Atmospheric Sciences 66 (3): 603–626.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Buizza, R., M. Miller, and T. Palmer. 1999. Stochastic representation of model uncertainties in the ECMWF ensemble prediction system.Quarterly Journal Royal Meteorological Society 125(560): 2887–2908</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Buizza, R., P. L. Houtekamer, Z. Toth, G. Pellerin, M. Wei, Y. Zhu, 2005: A Comparison of the ECMWF, MSC, and NCEP Global Ensemble Prediction Systems. Mon. Wea. Rev., 133, 1076-1097</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Cui, B., Z. Toth, Y. Zhu and D. Hou, 2012: Bias Correction For Global Ensemble Forecast, Weather and Forecasting, 27, 396-410</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Cui, B., Y. Zhu, Z. Toth and D. Hou, 2018: Development of Statistical Post-processor for NAEFS. To be submitted to Weather and Forecasting</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Guan, H., B. Cui, Y. Zhu, 2015: Improvement of Statistical Postprocessing Using GEFS Reforecast Information, Weather and Forecasting, Vol. 30, 841-854</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Guan, H. and Y. Zhu, 2017: Development of Verification Methodology for Extreme Weather Forecasts. Wea. Forecasting, 32, 470-491</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Guan, H., Y. Zhu, E. Sinsky, W. Li, X. Zhou, D. Hou, C. Melhauser and R. Wobus, 2019: Systematic Error Analysis and Calibration of 2-m Temperature for the NCEP GEFS Reforecast of SubX Project. Wea. Forecasting, Vol. 34, 361-376.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Guan, H., Y. Zhu, E. Sinsky, B. Fu, X. Zhou, W. Li, X. Xue, D. Hou, B. Cui, and J. Peng, 2020: The NCEP GEFS-v12 Reforecasts to Support Subseasonal and Hydrometeorological Applications, STI Climate Bulletin, 79-82, <a href="https://doi.org/10.25923/t4qa-ae63">https://doi.org/10.25923/t4qa-ae63</a></span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Hamill, T. M., G. T. Bates, J. S. Whitaker, D. R. Murray, M. Fiorino, T. J. Galarneau, Jr., Y. Zhu, and W. Lapenta, 2013: NOAA's Second-generation Global Medium-range Ensemble Reforecast Data Set, Bull Amer. Meteor. Soc., 95, 1553-1565</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Hamill, T., J. Whitaker and S. L. Mullen, 2006: Reforecasts: An important dataset for improving weather predictions. Bull. Amer. Meteor. Soc.,87, 33–46.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Hou, D., Z. Toth, Y. Zhu, W. Yang and R. Wobus, 2012: "A Stochastic Total Tendency Perturbation Scheme Representing Model- Related Uncertainties in the NCEP Global Ensemble Forecast System" Submitted to Tellus-A)</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Han, J., Wang, W., Kwon, Y. C., Hong, S.-Y., Tallapragada, V., & Yang, F., 2017:. Updates in the NCEP GFS cumulus convection schemes with scale and aerosol awareness. Wea.Forecasting, 32(5), 2005–2017. <a href="https://doi.org/10.1175/WAF-D-17-0046.1">https://doi.org/10.1175/WAF-D-17-0046.1</a></span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Hou, D., Z. Toth, Y. Zhu, and W. Yang, 2008: Evaluation of the impact of the stochastic perturbation schemes on global ensemble forecast. Proc. 19th Conf. on Probability and Statistics, New Orleans, LA, Amer. Meteor. Soc. (Available online at <a href="https://ams.confex.com/ams/88Annual/webprogram/Paper134165.html">https://ams.confex.com/ams/88Annual/webprogram/Paper134165.html</a>.)</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Hou, D., M. Charles, Y. Luo, Z. Toth, Y. Zhu, R. Krzysztofowicz, Y. Lin, P. Xie, D-J. Seo, M. Pena and B. Cui, 2012: Climatology-Calibrated Precipitation Analysis at Fine Scales: Statistical Adjustment of STAGE IV towards CPC Gauge-Based Analysis, Journal of Hydrometeorology Vol. 15 2542-2557.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Li, W., Y. Zhu, X. Zhou, D. Hou, E. Sinsky, C. Melhauser, M. Pena, H. Guan and R. Wobus, 2018: Evaluating the MJO Forecast Skill from Different Configurations of NCEP GEFS Extended Forecast. Climate Dynamics, 52, 4923–4936. <a href=" https://doi.org/10.1007/s00382-018-4423-9">https://doi.org/10.1007/s00382-018-4423-9</a></span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Li, W., H. Guan, Y. Zhu, X. Zhou, B. Fu, D. Hou, E. Sinsky, and X. Xue, 2020: Prediction Skill of the MJO, NAO and PNA in the NCEP FV3-GEFS 35-day Experiments, STI Climate Bulletin, 124-127, <a href="https://doi.org/10.25923/t4qa-ae63">https://doi.org/10.25923/t4qa-ae63</a></span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Liu, Q., S. J. Lord, N. Surgi, Y. Zhu, R. Wobus, Z. Toth and T. Marchok, 2006: Hurricane Relocation in Global Ensemble Forecast System, Preprints, 27th Conf. on Hurricanes and Tropical Meteorology, Monterey, CA, Amer. Meteor. Soc., P5.13.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Ma, J., Y. Zhu, D. Wobus and P. Wang, 2012: An Effective Configuration of Ensemble Size and Horizontal Resolution for the NCEP GEFS, Advance in Atmospheric Sciences, Vol. 29, No. 4, 782-794</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Ma, J., Y. Zhu, D. Hou, X. Zhou and M. Pena, 2014: Ensemble Transform with 3D Rescaling Initialization Method, Monthly Weather Review, Vol. 142, 4053-4073</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Palmer, T. N., R. Buizza, F. Doblas-Reyes, T. Jung, M. Leutbecher, G. Shutts, M. Steinheimer, and A. Weisheimer, 2009: Stochastic Parametrization and Model Uncertainty. ECMWF Tech. Memo. 598, 44.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Saha, S., and Coauthors, 2010: The NCEP Climate Forecast System Reanalysis. Bull. Amer. Meteor. Soc., 91, 1015–1057.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Shutts, G., 2005: A kinetic energy backscatter algorithm for use in ensemble prediction systems. Quart. J. Roy. Meteor. Soc., 131, 3079-3102.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Toth, Z. and E. Kalnay, 1993: Ensemble Forecasting at NMC: The Generation of Perturbations. Bull. Amer. Meteor. Soc., 74, 2317–2330.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Toth, Z., E. Kalnay, S. Tracton, R. Wobus, and J. Irwin, 1997: A synoptic evaluation of the NCEP ensemble. Wea. Forecasting, 12, 140–153.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Toth, Z., and E. Kalnay, 1997: Ensemble forecasting at NCEP and the breeding method. Mon. Wea. Rev., 125, 3297-3319. Wea. Forecasting, 12, 140–153.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Toth. Z., Y. Zhu and T. Marchok, 2001: The Use of Ensembles to Identify Forecasts with Small and Large Uncertainty. Wea. Forecasting, Vol. 16, 436-477.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Wei, M., Z. Toth, R. Wobus, and Y. Zhu, C. H. Bishop, X. Wang, 2006: Ensemble Transform Kalman Filter-based ensemble perturbations in an operational global prediction system at NCEP. Tellus 58A, 28-44</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Wei, M., Z. Toth, R. Wobus, and Y. Zhu, 2008: Initial Perturbations Based on the Ensemble Transform (ET) Technique in the NCEP Global Operational Forecast System, Tellus 59A, 62-79</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Whitaker, Jeffrey S., Thomas M. Hamill, Xue Wei, Yucheng Song, Zoltan Toth, 2008: Ensemble Data Assimilation with the NCEP Global Forecast System. Mon. Wea. Rev., 136, 463-482.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Zhou, X., Y. Zhu, D. Hou, and D. Kleist 2016: Comparison of the Ensemble Transform and the Ensemble Kalman Filter in the NCEP Global Ensemble Forecast System. Wea.  Forecasting, Vol. 31, 2058-2074.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Zhou, X., Y. Zhu, D. Hou, Y. Luo, J. Peng and R. Wobus, 2017: The NCEP Global Ensemble Forecast System with the EnKF Initialization. Wea. Forecasting, 32, 1989-2004.&nbsp; </span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Zhou, X., Y. Zhu, B. Fu, D. Hou, J. Peng, Y. Luo and W. Li, 2019: The Development of Next NCEP Global Ensemble Forecast System. STI Climate Bulletin, 159-163.&nbsp; </span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Zhou, X., Y. Zhu, D. Hou, and D. Kleist, 2016: Comparison of the Ensemble Transform and the Ensemble Kalman Filter in the NCEP Global Ensemble Forecast System. Wea. Forecasting, Vol. 31, 2058-2074.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Zhu, Y., Z. Toth, R. Wobus, D. Richardson, and K. Mylne, 2002: On the Economic Value of Ensemble Based Weather Forecasts. Bulletin of American Meteorological Society, Vol. 83, 73-83.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Zhu, Y. 2005: Ensemble Forecast: A New Approach to Uncertainty and Predictability. Advance in Atmospheric Sciences, Vol. 22, No. 6, 781-788.</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Zhu, Y., and Y. Luo, 2014: Precipitation Calibration Based on Frequency Matching Method (FMM), Weather and Forecasting, Vol. 30, 1109-1124</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Zhu, Y., X. Zhou, M. Pena, W. Li, C. Melhauser, and D. Hou, 2017: Impact of Sea Surface Temperature Forcing on Weeks 3 & 4 Forecast Skill in the NCEP Global Ensemble Forecasting System. Wea. Forecasting, Vol. 32, 2159-2173 DOI: 10.1175/WAF-D-17-0093.1</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Zhu, Y., W. Li, X. Zhou, and D. Hou, 2019: Stochastic Representation of NCEP GEFS to Improve Subseasonal Forecasts. Current trends in the Representation of Physical Processes in Weather and Climate Models, Editors: Randall, D.A., Srinivasan, J., Nanjundiah, R.A., Mukhopadhyay, P. Springer Atmospheric Sciences, 317-328</span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span lang="en-US">Zhu, Y., X. Zhou, W. Li, D. Hou, C. Melhauser, E. Sinsky, M. Pena, B. Fu, H. Guan, W. Kolczynski, R. Wobus and V. Tallapragada, 2018: Towards the Improvement of Sub-Seasonal Prediction in the NCEP Global Ensemble Forecast System (GEFS). Journal of Geophysical Research, 6732-6745, <a href="https://doi.org/10.1029/2018JD028506">https://doi.org/10.1029/2018JD028506</a></span></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"></span></p>

<p class="western" style="margin-top: 0.04in; margin-bottom: 0.08in; line-height: 100%" lang="en-GB" align="justify"><span style="font-size:16px;"><span style="font-family:arial,helvetica,sans-serif;"><a href="http://www.weather.gov/disclaimer"><b><em>National Weather Service Web Page Disclaimer</em></b></a></span></span></p>
			  </div>
     
	  <br/>
      
    </main>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <!--<script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
	  <script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>-->
	  
	  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>

</body>
      
</html>
 
