<?php include('../header.php') ?>
<div id="models-table-container">
  <h1 class="text-center" id="global-model-heading">
    GLOBAL/HEMISPHERIC models at JNWPU/NMC/NCEP - a HISTORY!
</h1>
    <div id="inner-model-global-container">
        <div id="model-table">
        <table class="table table-hover">
        <TR><TH STYLE="color:blue">MODEL</TH><TH STYLE="color:blue">TPB#</TH> <TH STYLE="color:blue">Birth-date</TH><TH STYLE="color:blue">Removal-date</TH> <TH STYLE="color:blue">FCST length (hrs)</TH>
<TR><TD>Charney's Princeton 3-Level</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD>
<TR><TD>Thompson/Gates' Thermotropic 2-Level</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD>
<TR><TD><B>Barotropic</B></TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>5/6/55</TD><TD ALIGN=CENTER>6/93</TD><TD ALIGN=CENTER>36</TD>
<TR><TD ALIGN=RIGHT>*<I STYLE="color:red">barotropic is the remaining operational model</I></TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>8/22/58</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>72</TD>
<TR><TD><B>3-Level</B> (filtered equation), plus</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>1962</TD><TD ALIGN=CENTER>6/6/66</TD><TD ALIGN=CENTER>36</TD>
<TR><TD ALIGN=RIGHT>*Barotropic extension</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>96</TD>
<TR><TD><B>Reed Surface</B> (1000mb) model, 2-Level</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>1962</TD><TD ALIGN=CENTER>6/6/66</TD><TD ALIGN=CENTER>-</TD>
<TR><TD><B>6-Layer Primitive Equation (6LPE)</B></TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>6/6/66</TD><TD ALIGN=CENTER>1/19/78</TD><TD ALIGN=CENTER>36</TD>
<TR><TD ALIGN=RIGHT>*Barotropic extension</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>1970</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>144+</TD>
<TR><TD><B>Limited-area Fine Mesh (LFM)</B></TD><TD ALIGN=CENTER>67</TD><TD ALIGN=CENTER>9/29/71</TD><TD ALIGN=CENTER>3/11/79</TD><TD ALIGN=CENTER>24</TD>
<TR><TD ALIGN=RIGHT>*fcst length change</TD><TD ALIGN=CENTER>129</TD><TD ALIGN=CENTER>1975</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>36</TD>
<TR><TD ALIGN=RIGHT>*fcst length change</TD><TD ALIGN=CENTER>162</TD><TD ALIGN=CENTER>1976</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>48</TD>
<TR><TD><B>Global 8-Layer PE </B><I STYLE="color:red">(FINAL analysis only)</I></TD><TD ALIGN=CENTER>115</TD><TD ALIGN=CENTER>1974</TD><TD ALIGN=CENTER>1976</TD><TD ALIGN=CENTER>12</TD>
<TR><TD><B>Global 9-Layer PE </B><I STYLE="color:red">(FINAL analysis only)</I></TD><TD ALIGN=CENTER>258</TD><TD ALIGN=CENTER>1976</TD><TD ALIGN=CENTER>5/80</TD><TD ALIGN=CENTER>12</TD>
<TR><TD><B>Global 3-Layer PE </B>(support for</TD><TD ALIGN=CENTER>215</TD><TD ALIGN=CENTER>12/77</TD><TD ALIGN=CENTER>4/15/81</TD><TD ALIGN=CENTER>264</TD>
<TR><TD ALIGN=RIGHT>6-10 day extended fcst)</TD><TD ALIGN=CENTER>257</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD>
<TR><TD><B>7-Layer PE </B>(fine mesh), plus</TD><TD ALIGN=CENTER>218</TD><TD ALIGN=CENTER>1/19/78</TD><TD ALIGN=CENTER>8/15/80</TD><TD ALIGN=CENTER>84</TD>
<TR><TD ALIGN=RIGHT>*Barotropic extension</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>144+</TD>
<TR><TD ALIGN=RIGHT>*coarse mesh 4th order extension:</TD><TD ALIGN=CENTER>272</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD>
<TR><TD ALIGN=RIGHT><I STYLE="color:red">(1) as BACKUP model</I></TD><TD ALIGN=CENTER>273</TD><TD ALIGN=CENTER>8/8/79</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD>
<TR><TD ALIGN=RIGHT>(2) as OPNL model</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>1980</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>144</TD>
<TR><TD><B>Moveable Fine Mesh (MFM)</B></TD><TD ALIGN=CENTER>259</TD><TD ALIGN=CENTER>1978</TD><TD ALIGN=CENTER>1988</TD><TD ALIGN=CENTER>48</TD>
<TR><TD ALIGN=RIGHT>*hurricane model</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=RIGHT STYLE="color:red"><I>on call as needed</I></TD>
<TR><TD><B>7L LFM (LFM-II)</B></TD><TD ALIGN=CENTER>255</TD><TD ALIGN=CENTER>3/11/79</TD><TD ALIGN=CENTER>6/93</TD><TD ALIGN=CENTER>-</TD>
<TR><TD ALIGN=RIGHT>*4th order differencing</TD><TD ALIGN=CENTER>300</TD><TD ALIGN=CENTER>1981</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD>
<TR><TD><B>Global Spectral</B> :</TD><TD ALIGN=CENTER>282</TD><TD ALIGN=CENTER>8/15/80</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>48</TD>
<TR><TD ALIGN=RIGHT>*coarse resolutions extension</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>3/81</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>144/60 at 00Z/12Z</TD>
<TR><TD ALIGN=RIGHT>*Medium-Range Forecast(MRF)</TD><TD ALIGN=CENTER>349</TD><TD ALIGN=CENTER>4/17/85</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>240 at 00Z</TD>
<TR><TD ALIGN=RIGHT>*Aviation (AVN) <I STYLE="color:red">not the MRF</I></TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>===></TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>72 at 00Z/12Z</TD>
<TR><TD ALIGN=RIGHT>*Global Ensembles</TD><TD ALIGN=CENTER>471</TD><TD ALIGN=CENTER>12/92</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD>
<TR><TD><B>Nested Grid Model (NGM)</B></TD><TD ALIGN=CENTER>345,350</TD><TD ALIGN=CENTER>3/27/85</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>48</TD>
<TR><TD><B>Ocean Wave (2nd generation)</B> at 00Z,12Z :</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD>
<TR><TD ALIGN=RIGHT>*Global</TD><TD ALIGN=CENTER>364</TD><TD ALIGN=CENTER>10/86</TD><TD ALIGN=CENTER>10/12/94</TD><TD ALIGN=CENTER>72</TD>
<TR><TD ALIGN=RIGHT>*Gulf of Mexico</TD><TD ALIGN=CENTER>381</TD><TD ALIGN=CENTER>8/17/91</TD><TD ALIGN=CENTER>10/23/97</TD><TD ALIGN=CENTER>48</TD>
<TR><TD ALIGN=RIGHT>*Gulf of Alaska</TD><TD ALIGN=CENTER>427</TD><TD ALIGN=CENTER>4/19/94</TD><TD ALIGN=CENTER>3/00</TD><TD ALIGN=CENTER>48</TD>
<TR><TD><B>Quasi-Lagrangian (QLM)</B></TD><TD ALIGN=CENTER>377</TD><TD ALIGN=CENTER>1988</TD><TD ALIGN=CENTER>6/6/95</TD><TD ALIGN=CENTER>72</TD>
<TR><TD ALIGN=RIGHT>*hurricane model</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=RIGHT STYLE="color:red"><I>on call as needed</I></TD>
<TR><TD><B>Early Eta</B></TD><TD ALIGN=CENTER>412</TD><TD ALIGN=CENTER>6/93</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>48</TD>
<TR><TD><B>Rapid Update Cycle (RUC)</B></TD><TD ALIGN=CENTER>416,429</TD><TD ALIGN=CENTER>9/27/94</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>12 <I>(8 times/day)</I></TD>
<TR><TD><B>Ocean Wave - WAM </B> at 00Z,12Z:</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD>
<TR><TD ALIGN=RIGHT>*Global</TD><TD ALIGN=CENTER>426</TD><TD ALIGN=CENTER>10/12/94</TD><TD ALIGN=CENTER>3/00</TD><TD ALIGN=CENTER>72</TD>
<TR><TD ALIGN=RIGHT>*East Coast+Gulf Mexico</TD><TD ALIGN=CENTER>446</TD><TD ALIGN=CENTER>10/23/97</TD><TD ALIGN=CENTER>3/00</TD><TD ALIGN=CENTER>48</TD>
<TR><TD><B>GFDL Multipli-Nested Moveable Mesh</B></TD><TD ALIGN=CENTER>424</TD><TD ALIGN=CENTER>6/6/95</TD><TD ALIGN=CENTER>6/1/01</TD><TD ALIGN=CENTER>78</TD>
<TR><TD ALIGN=RIGHT>*hurricane model</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=RIGHT STYLE="color:red"><I>on call as needed at 00Z/12Z</I></TD>
<TR><TD><B>Regional Spectral Model </B><I STYLE="color:teal">(RSM Hawaii)</I></TD><TD ALIGN=CENTER>444</TD><TD ALIGN=CENTER>6/97</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>48</TD>
<TR><TD><B>Sea Ice Drift Model</B></TD><TD ALIGN=CENTER>435</TD><TD ALIGN=CENTER>10/20/97</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>384</TD>
<TR><TD><B>NOAA Wavewatch III (NWW3)</B> at 00Z,12Z:</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>-</TD>
<TR><TD ALIGN=RIGHT>*Global</TD><TD ALIGN=CENTER>453</TD><TD ALIGN=CENTER>3/00</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>126</TD>
<TR><TD ALIGN=RIGHT>*Alaska</TD><TD ALIGN=CENTER>456</TD><TD ALIGN=CENTER>3/00</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>126</TD>
<TR><TD ALIGN=RIGHT>*W. N-Atlantic</TD><TD ALIGN=CENTER>459</TD><TD ALIGN=CENTER>3/00</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>126</TD>
<TR><TD ALIGN=RIGHT>*N-Atl hurricane</TD><TD ALIGN=CENTER>478</TD><TD ALIGN=CENTER>6/01</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>72</TD>
<TR><TD ALIGN=RIGHT>*E. N-Pacific</TD><TD ALIGN=CENTER>491</TD><TD ALIGN=CENTER>5/02</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>126</TD>
<TR><TD ALIGN=RIGHT>*N-Pac hurricane</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>8/03</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>72</TD>
<TR><TD><B>GFDL/URI Hurricane-Ocean Coupled</B></TD><TD ALIGN=CENTER>472B</TD><TD ALIGN=CENTER>6/1/01</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>126</TD>
<TR><TD ALIGN=RIGHT>*hurricane model</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=RIGHT STYLE="color:red"><I>on call as needed at 0,6,12,18Z</I></TD>
<TR><TD><B>Seasonal Forecast Model (SFM)</B></TD><TD ALIGN=CENTER>480</TD><TD ALIGN=CENTER>2001</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>7 months</TD> 
<TR><TD><B>Regional (short-range) Ensembles </B><I>(Eta,RSM)</I></TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>4/01</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>63</TD>
<TR><TD><B>Hi-Res Window </B><I>(nested meso-Eta)</I></TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>6/01</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>48</TD>
<TR><TD ALIGN=RIGHT>*<I STYLE="color:red">when no hurricane model run</I></TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD>
<TR><TD><B>NOAA Regional (layered) Ocean (POM) </B></TD><TD ALIGN=CENTER>489</TD><TD ALIGN=CENTER>4/02</TD><TD ALIGN=CENTER STYLE="color:orange"><I>still running</I></TD><TD ALIGN=CENTER>48</TD>
        </table>
        </div>
    </div>
</div>

<?php include('../footer.php') ?>