<?php include '../header.php';?>

    <link rel="stylesheet" href="https://www.emc.ncep.noaa.gov/emc/css/main/emc-about.css" media="all">
	<link rel="stylesheet" href="https://www.emc.ncep.noaa.gov/emc/css/main/emc-content-template.css" media="all">

<div class="container-fluid  main-content">
		<section class="main-first-content-row">
			<div class="container">
				<div class="row">
				  <div class="col-lg-12"><h2 class="page-title">DOCUMENTATION AND SUPPORT<h2></div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<div class="col-lg-3 left-side-bar">
							<ul class="list-group">
								<li class="list-group-item"><a href="https://www.emc.ncep.noaa.gov/emc/pages/guidance-systems.php" class="see-link">Guidance Systems</a>
            						<ul class="list-group">
                						<li class="list-group-item"><a href="https://www.emc.ncep.noaa.gov/emc/pages/ncep-numerical-forecast-systems.php">NCEP Numerical Forecast/Analysis Systems</li>
                                        <li class="list-group-item"><a href="https://www.emc.ncep.noaa.gov/emc/pages/verification.php">Verification</a></li>
                                        <li class="list-group-item"><a href="https://www.emc.ncep.noaa.gov/emc/pages/emc-research-developmental-graphics.php">EMC Research and Development Graphics</a></li>
                                        <li class="list-group-item"><a href="https://www.emc.ncep.noaa.gov/emc/pages/nomads.php">NOMADS Product Site</a></li>
                                        <li class="list-group-item"><a href="https://www.emc.ncep.noaa.gov/emc/pages/documentation-support.php" class="see-link">Documentation and Support</a></li>
                                     </ul>
                                 </li>
							</ul>
						  
						</div>
						
						<div class="col-lg-9">
							<div class="seminar-content-page">
								<p style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:16px;">EMC online documentation includes information on specific forecasts systems, numerical data, and research publications.</span></p>

                                <p style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong><span style="font-size:14px;"><span style="font-size:16px;">1. Online Documentation on NWS Vlab and GitHub&nbsp;</span> </span></strong></p>
                                
                                <ul>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="https://github.com/ufs-community/ufs-weather-model/wiki">Unified Forecast System (a.k.a FV3GFS) on GitHub</a></strong></span>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="https://noaa-emc.github.io/FV3_Dycore_ufs-v2.0.0/html/index.html">FV3 Dynamic Core Documentation</a></strong></span>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="https://vlab.noaa.gov/web/environmental-modeling-center">EMC VLab Community</a></strong></span>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="https://noaa-emc.github.io/UPP">Unified Post-Processor Documentation</a></strong></span>
                                
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong><a href="https://noaa-emc.github.io/NEMS_doc_ufs-v2.0.0/index.html"><span style="font-size:14px;">NEMS Overview and Documentation</span></a> </strong></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="https://vlab.noaa.gov/group/715073/home">RTMA/URMA Community</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong><a href="https://vlab.noaa.gov/redmine/projects/comgsi?jump=welcome"><span style="font-size:14px;">GSI Analysis Code Community on VLab</span></a></strong></li>
                                </ul>
                                
                                <p style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:18px;"><strong>2. Other Sources of Documentation</strong></span></p>
                                
                                <p style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;">This is a list of various web sites and documents available online which provide detailed information on aspects of the EMC's Guidance Systems.</span></p>
                                
                                <ul style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><a href="https://www.emc.ncep.noaa.gov/emc/docs/EMC_Pubs_List.pdf"><strong>Recent EMC Publications</strong></a></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><a href="https://www.emc.ncep.noaa.gov/emc/pages/model_history/modeltables/modelTable.php"><strong>JNWPU/NMC/NCEP Model History Tables (1955-Present), with links to documentation if available</strong></a></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><a href="https://www.gfdl.noaa.gov/fv3/"><strong>FV3 Documentation at GFDL</strong></a></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><a href="http://www.lib.ncep.noaa.gov/ncepofficenotes/"><strong>NCEP Office Notes (1955 - Present)</strong></a></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="https://repository.library.noaa.gov/cbrowse?pid=noaa:6&amp;parentId=noaa:6">NWS Documents at the NOAA Institutional Repository</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/gfs/documentation.php">Global Forecast System Reference Page</a> (includes history of <a href="http://www.emc.ncep.noaa.gov/gmb/STATS/html/model_changes.html">GFS upgrades since 1980</a>)</strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong><span style="font-size:14px;">Global Ensemble Forecast System and NAEFS :</span><span style="font-size:14px;"> </span><a href="http://www.emc.ncep.noaa.gov/gmb/yzhu/html/ENS_IMP.html"><span style="font-size:14px;">Implementation Documents</span></a><span style="font-size:14px;">, <a href="http://www.emc.ncep.noaa.gov/gc_wmb/wli/html/doc_journal.html">Publications</a></span></strong></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong><a href="http://cfs.ncep.noaa.gov/cfsv2/docs.html"><span style="font-size:14px;">Climate Forecast System Version 2 Documentation</span></a></strong></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="https://www.emc.ncep.noaa.gov/users/meg/home/table.html">NCEP Model Specification Table </a>(Atmospheric Models only)</strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://www.emc.ncep.noaa.gov/mmb/mmbpll/misc/NAM_2017.pdf">NAM System Description (as of March 2017)</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/nam/references.php#TAB4">Chronological List of NCEP Mesoscale system implementations since 1993</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://www.lib.ncep.noaa.gov/ncepofficenotes/files/on438.pdf">Original NCEP Office Note on EMC Post-Processor (from 2001)</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://www.emc.ncep.noaa.gov/mmb/research/FAQ-meso.html">Mesoscale Systems (mostly NAM) FAQ page</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="https://www.emc.ncep.noaa.gov/mmb/SREF/pcpanl/">EMC Hourly/6-Hourly Precipitation Analysis Page</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://www.emc.ncep.noaa.gov/mmb/SREF/reference.html">SREF References/Documents</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://rapidrefresh.noaa.gov/hrrr/">HRRR Main Page at GSL/ESRL</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://rapidrefresh.noaa.gov/">RAP Main Page at GSL/ESRL</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong><a href="http://www.emc.ncep.noaa.gov/mmb/aq/NAQFC-reports.html"><span style="font-size:14px;">NCEP Air Quality Model Reports<span style="font-size:14px;"></span></span></a></strong></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://polar.ncep.noaa.gov/waves/wavewatch/">WAVEWATCH III</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://polar.ncep.noaa.gov/global/about/?">Global RTOFS</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://polar.ncep.noaa.gov/mmab/notes.shtml">Marine Modeling / Analysis Systems ; comprehensive list of documents since 1987</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://www.emc.ncep.noaa.gov/gc_wmb/vxt/HWRF/about.php?branch=doc">HWRF</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://www.emc.ncep.noaa.gov/gc_wmb/vxt/HMON/about.php?branch=doc">HMON</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="http://nomads.ncep.noaa.gov/index.shtml">NOMADS Operational Model Archive</a></strong></span></li>
                                	<li style="margin-top: 0px; line-height: 28.8px; text-align: justify; color: rgb(0, 0, 0); font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:14px;"><strong><a href="https://www.emc.ncep.noaa.gov/users/meg/home/">EMC Model Evaluation Group</a></strong></span></li>
                                </ul>
                                								
                                 																
                                 <div class="container-fluid">
                                     <div class="row"></div>
                                 </div>
     					</div>	
					</div>
						
						
					</div>
					
					
				</div>
			
			</div>
		</section>
	</div>

<script type="text/javascript">
 // Configure/customize these variables.
    var showChar = 100;  // How many characters are shown by default
    var ellipsestext = "...";
    var moretext = "Show more >";
    var lesstext = "Show less";
    

    $('.more').each(function() {
        var content = $(this).html();
 
        if(content.length > showChar) {
 
            var c = content.substr(0, showChar);
            var h = content.substr(showChar, content.length - showChar);
 
            var html = c + '<span class="moreellipses">' + ellipsestext+ '&nbsp;</span><span class="morecontent"><span>' + h + '</span>&nbsp;&nbsp;<a href="" class="morelink">' + moretext + '</a></span>';
 
            $(this).html(html);
        }
 
    });
 
    $(".morelink").click(function(){
        if($(this).hasClass("less")) {
            $(this).removeClass("less");
            $(this).html(moretext);
        } else {
            $(this).addClass("less");
            $(this).html(lesstext);
        }
        $(this).parent().prev().toggle();
        $(this).prev().toggle();
        return false;
    });
</script>
<?php include '../footer.php';?>
